# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_type', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('client_alias', models.CharField(max_length=500)),
                ('client_address', models.CharField(max_length=500)),
                ('tin_no', models.IntegerField()),
                ('pan_no', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('state', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 20, 7, 52, 42, 1229))),
            ],
        ),
    ]
