# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=100)),
                ('consultant_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=700)),
                ('consultant_address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('bank_MICR_code', models.CharField(max_length=100)),
                ('sales_tax_reg_no', models.IntegerField()),
                ('vat_reg_no', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=200)),
                ('tin_no', models.IntegerField()),
                ('pan_no', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('state', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 20, 7, 52, 42, 57606))),
            ],
        ),
    ]
