# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kst_no', models.CharField(default=None, max_length=100, null=True)),
                ('cst_no', models.CharField(default=None, max_length=100, null=True)),
                ('service_tax_no', models.CharField(default=None, max_length=100, null=True)),
                ('esi_no', models.CharField(default=None, max_length=100, null=True)),
                ('pf_no', models.CharField(default=None, max_length=100, null=True)),
                ('income_tax_pan_number', models.CharField(default=None, max_length=100, null=True)),
                ('work_contract_tax_number', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidityOfLicences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shops_and_establishments', models.CharField(default=None, max_length=200, null=True)),
                ('contract_labour_act', models.CharField(default=None, max_length=200, null=True)),
                ('others', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('client_name', models.CharField(max_length=300)),
                ('client_alias', models.CharField(max_length=200)),
                ('consultant_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('year_of_establishment', models.IntegerField()),
                ('name_of_the_propreiter', models.CharField(max_length=500, null=True)),
                ('nature_of_services_offered', models.CharField(max_length=100)),
                ('previous_year_turnover', models.PositiveIntegerField(default=None)),
                ('income_tax_paid_and_cleared_till', models.CharField(default=None, max_length=100)),
                ('banker_details', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=500)),
                ('tin_no', models.CharField(default=None, max_length=100)),
                ('pan_no', models.CharField(default=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('state', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 7, 14, 15, 23, 12, 853000))),
                ('statutory_registrations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.StatutoryRegistrations')),
                ('validity_of_licences', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.ValidityOfLicences')),
            ],
        ),
    ]
