# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20160714_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validityoflicences',
            name='mst_no',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 14, 15, 41, 51, 691000)),
        ),
    ]
