# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20160714_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 7, 52, 42, 65763)),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[(b'contractor', b'CONTRACTOR'), (b'oem', b'OEM'), (b'supplier', b'SUPPLIER')], max_length=200),
        ),
    ]
